[project]
name = "dr-exec"
version = "0.1.0"
description = "Execution utils with carefully chosen defaults"
readme = "README.md"
authors = [
    { name = "Danielle Rothermel", email = "danielle.rothermel@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "dr-serialize==0.1.0",
    "pydantic==2.13.4",
]

[build-system]
requires = ["uv_build>=0.11.25,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.1",
    "ty>=0.0.65",
]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
include = ["scripts/**/*.py", "src/**/*.py"]
line-length = 79

[tool.ty.src]
include = ["scripts", "src"]
exclude = ["nbs", "tests"]
