from __future__ import annotations

import dr_exec
from dr_exec.capabilities import protocols

EXPECTED_PUBLIC_API = (
    "AttemptId",
    "AutoPoolCapacity",
    "BudgetAxis",
    "BudgetExceededOutcome",
    "BudgetExceededOutcomeRecord",
    "Budgets",
    "ByteBudget",
    "CancelToken",
    "CancelledOutcome",
    "CancelledOutcomeRecord",
    "CapacitySource",
    "CompleteRecordReceipt",
    "CompletedExecution",
    "ContainmentProfile",
    "CountBudget",
    "DeclarationError",
    "DegradedRecordReceipt",
    "DirectoryRunStore",
    "DurationBudget",
    "EffectivePoolCapacity",
    "EnvGrant",
    "EnvGrantKind",
    "EnvGrantRecord",
    "EnvVar",
    "ExecutionAttribution",
    "ExecutionAttributionRecord",
    "ExecutionCompletion",
    "ExecutionId",
    "ExecutionJob",
    "ExecutionMeasurements",
    "ExecutionOutcome",
    "ExecutionOutcomeRecord",
    "ExecutionPool",
    "ExecutionPoolConfig",
    "ExecutionPoolState",
    "ExecutionResult",
    "ExecutionResultRecord",
    "ExecutionSubmission",
    "ExecutionTarget",
    "ExecutionTargetKind",
    "ExecutionTargetRecord",
    "Executor",
    "ExecutorFailure",
    "ExecutorSelfBudgets",
    "ExitedOutcome",
    "ExitedOutcomeRecord",
    "FailureOwner",
    "FakeExecutor",
    "FakeRecordReceipt",
    "FinalizableRun",
    "FinalizedRecord",
    "FiniteByteLimit",
    "FiniteCountLimit",
    "FiniteDurationLimit",
    "FiniteOutput",
    "FixedPoolCapacity",
    "IsolatedHostPythonRuntime",
    "JobId",
    "LimitKind",
    "OutcomeKind",
    "OutputArtifactRecord",
    "OutputArtifactRecords",
    "OutputBudget",
    "OutputOverflowPolicy",
    "PayloadOutputRecords",
    "PayloadOutputs",
    "PayloadRetentionBudget",
    "PoolCapacity",
    "PreparedPythonProcess",
    "PreparedRecord",
    "PreparedRun",
    "ProcessExecutor",
    "ProcessRecord",
    "ProtocolFailedOutcome",
    "ProtocolFailedOutcomeRecord",
    "ProtocolFailureCode",
    "RealRecordReceipt",
    "RecordLoadError",
    "RecordReceipt",
    "RecordReceiptKind",
    "RecordState",
    "RecordingFailure",
    "RetainedPayloadStream",
    "RetainedPayloadStreamRecord",
    "RunDeclaration",
    "RunRecord",
    "RunRecordHeader",
    "RunStore",
    "RunningRecord",
    "RunningRun",
    "Runtime",
    "RuntimeKind",
    "RuntimeRecord",
    "SignaledOutcome",
    "SignaledOutcomeRecord",
    "SpawnAbsentOutcome",
    "SpawnAbsentOutcomeRecord",
    "SpawnFailedOutcome",
    "SpawnFailedOutcomeRecord",
    "StreamRetentionBudget",
    "TrustedCommandTarget",
    "TrustedCommandTargetRecord",
    "UnbudgetedLimit",
    "UnbudgetedOutput",
    "UntrustedCommandTarget",
    "UntrustedCommandTargetRecord",
    "UntrustedPythonTarget",
    "UntrustedPythonTargetRecord",
)


def test_the_complete_public_api_is_explicit_and_sorted() -> None:
    assert dr_exec.__all__ == list(EXPECTED_PUBLIC_API)
    assert list(EXPECTED_PUBLIC_API) == sorted(set(EXPECTED_PUBLIC_API))


def test_every_public_name_resolves_from_the_package() -> None:
    missing = [
        name for name in EXPECTED_PUBLIC_API if not hasattr(dr_exec, name)
    ]
    assert missing == []


def test_only_the_three_named_protocols_are_capability_boundaries() -> None:
    assert set(protocols.__all__) == {
        "Executor",
        "RunStore",
        "Runtime",
    }
